### ISSUE TITLE
[Question] Are the labels assumed to be one-hot encoded?

### ISSUE THREAD

**Issue by ClonedOne** [cg563/simple-blackbox-attack#13]
Hello and thank you for sharing your code.

I'd like to ask what is the format of the labels to use? are they assumed to be one-hot encoded or just integers?

Thank you!

**Comment by cg563** [comment]
The code assumes integer labels from 0 to K-1, same as when training a model in PyTorch.

Let me know if you have any other question.

**Comment by ClonedOne** [comment]
Thank you very much for the clarification!
