### ISSUE TITLE
why the block_idct function is used in the code?

### ISSUE THREAD

**Issue by fzgang111** [cg563/simple-blackbox-attack#14]
I have read the paper and the code.The dct is used in the paper,but why the block_idct function is used in the code?I am very confused. @cg563

**Comment by cg563** [comment]
The `block_idct` function is a strict generalization of IDCT. If you set `block_size` = image_size`, where `image_size` is the height and width of your image, then it should be identical to applying IDCT independently across the color channels. Hope this helps.

**Comment by fzgang111** [comment]
> The `block_idct` function is a strict generalization of IDCT. If you set `block_size` = image_size`, where `image_size` is the height and width of your image, then it should be identical to applying IDCT independently across the color channels. Hope this helps.

Thank you. I know why the block_idct is used.
