### ISSUE TITLE
about the order of coordinate selection

### ISSUE THREAD

**Issue by fzgang111** [cg563/simple-blackbox-attack#17]
Hi. I have read the literature and code. I want to know where the diagonal order and block order come from? Could you give me some references?

**Comment by cg563** [comment]
Both are randomized sampling methods that are biased towards selecting the top-left corner entries. You can see their definition in https://github.com/cg563/simple-blackbox-attack/blob/master/utils.py#L146 and https://github.com/cg563/simple-blackbox-attack/blob/master/utils.py#L169.

All results in the paper on ResNet and DenseNet are produced using the block order with `initial_size=28` and `stride=7`. Hope this helps.
