### ISSUE TITLE
about run_simba_cifar.py

### ISSUE THREAD

**Issue by smileycapcake** [cg563/simple-blackbox-attack#21]
Hello, I run the code on CIFAR-10:  python run_simba_cifar.py --data_root ./pytorch-cifar/data/cifar-10-batches-py/ --model_ckpt ./pytorch-cifar/checkpoint/ckpt.pth --model ResNet18 --targeted
but there was an error:
Traceback (most recent call last):
  File "run_simba_cifar.py", line 43, in <module>
    model.load_state_dict(checkpoint['net'])
  File "/home/sugon/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.conv1.weight", "module.bn1.weight", "module.bn1.bias", "module.bn1.running_mean", "module.bn1.running_var", "module.layer1.0.conv1.weight", "module.layer1.0.bn1.weight", "module.layer1.0.bn1.bias", "module.layer1.0.bn1.running_mean", "module.layer1.0.bn1.running_var", "module.layer1.0.conv2.weight", "module.layer1.0.bn2.weight", "module.layer1.0.bn2.bias", "module.layer1.0.bn2.running_mean", "module.layer1.0.bn2.running_var", "module.layer1.1.conv1.weight", "module.layer1.1.bn1.weight", "module.layer1.1.bn1.bias", "module.layer1.1.bn1.running_mean", "module.layer1.1.bn1.running_var", "module.layer1.1.conv2.weight", "module.layer1.1.bn2.weight", "module.layer1.1.bn2.bias", "module.layer1.1.bn2.running_mean", "module.layer1.1.bn2.running_var", "module.layer2.0.conv1.weight", "module.layer2.0.bn1.weight", "module.layer2.0.bn1.bias", "module.layer2.0.bn1.running_mean", "module.layer2.0.bn1.running_var", "module.layer2.0.conv2.weight", "module.layer2.0.bn2.weight", "module.layer2.0.bn2.bias", "module.layer2.0.bn2.running_mean", "module.layer2.0.bn2.running_var", "module.layer2.0.shortcut.0.weight", "module.layer2.0.shortcut.1.weight", "module.layer2.0.shortcut.1.bias", "module.layer2.0.shortcut.1.running_mean", "module.layer2.0.shortcut.1.running_var", "module.layer2.1.conv1.weight", "module.layer2.1.bn1.weight", "module.layer2.1.bn1.bias", "module.layer2.1.bn1.running_mean", "module.layer2.1.bn1.running_var", "module.layer2.1.conv2.weight", "module.layer2.1.bn2.weight", "module.layer2.1.bn2.bias", "module.layer2.1.bn2.running_mean", "module.layer2.1.bn2.running_var", "module.layer3.0.conv1.weight", "module.layer3.0.bn1.weight", "module.layer3.0.bn1.bias", "module.layer3.0.bn1.running_mean", "module.layer3.0.bn1.running_var", "module.layer3.0.conv2.weight", "module.layer3.0.bn2.weight", "module.layer3.0.bn2.bias", "module.layer3.0.bn2.running_mean", "module.layer3.0.bn2.running_var", "module.layer3.0.shortcut.0.weight", "module.layer3.0.shortcut.1.weight", "module.layer3.0.shortcut.1.bias", "module.layer3.0.shortcut.1.running_mean", "module.layer3.0.shortcut.1.running_var", "module.layer3.1.conv1.weight", "module.layer3.1.bn1.weight", "module.layer3.1.bn1.bias", "module.layer3.1.bn1.running_mean", "module.layer3.1.bn1.running_var", "module.layer3.1.conv2.weight", "module.layer3.1.bn2.weight", "module.layer3.1.bn2.bias", "module.layer3.1.bn2.running_mean", "module.layer3.1.bn2.running_var", "module.layer4.0.conv1.weight", "module.layer4.0.bn1.weight", "module.layer4.0.bn1.bias", "module.layer4.0.bn1.running_mean", "module.layer4.0.bn1.running_var", "module.layer4.0.conv2.weight", "module.layer4.0.bn2.weight", "module.layer4.0.bn2.bias", "module.layer4.0.bn2.running_mean", "module.layer4.0.bn2.running_var", "module.layer4.0.shortcut.0.weight", "module.layer4.0.shortcut.1.weight", "module.layer4.0.shortcut.1.bias", "module.layer4.0.shortcut.1.running_mean", "module.layer4.0.shortcut.1.running_var", "module.layer4.1.conv1.weight", "module.layer4.1.bn1.weight", "module.layer4.1.bn1.bias", "module.layer4.1.bn1.running_mean", "module.layer4.1.bn1.running_var", "module.layer4.1.conv2.weight", "module.layer4.1.bn2.weight", "module.layer4.1.bn2.bias", "module.layer4.1.bn2.running_mean", "module.layer4.1.bn2.running_var".
        Unexpected key(s) in state_dict: "module.base.0.weight", "module.base.1.weight", "module.base.1.bias", "module.base.1.running_mean", "module.base.1.running_var", "module.base.1.num_batches_tracked", "module.layer5.root.conv.weight", "module.layer5.root.bn.weight", "module.layer5.root.bn.bias", "module.layer5.root.bn.running_mean", "module.layer5.root.bn.running_var", "module.layer5.root.bn.num_batches_tracked", "module.layer5.left_tree.root.conv.weight", "module.layer5.left_tree.root.bn.weight", "module.layer5.left_tree.root.bn.bias", "module.layer5.left_tree.root.bn.running_mean", "module.layer5.left_tree.root.bn.running_var", "module.layer5.left_tree.root.bn.num_batches_tracked", "module.layer5.left_tree.left_tree.conv1.weight", "module.layer5.left_tree.left_tree.bn1.weight", "module.layer5.left_tree.left_tree.bn1.bias", "module.layer5.left_tree.left_tree.bn1.running_mean", "module.layer5.left_tree.left_tree.bn1.running_var", "module.layer5.left_tree.left_tree.bn1.num_batches_tracked", "module.layer5.left_tree.left_tree.conv2.weight", "module.layer5.left_tree.left_tree.bn2.weight", "module.layer5.left_tree.left_tree.bn2.bias", "module.layer5.left_tree.left_tree.bn2.running_mean", "module.layer5.left_tree.left_tree.bn2.running_var", "module.layer5.left_tree.left_tree.bn2.num_batches_tracked", "module.layer5.left_tree.left_tree.shortcut.0.weight", "module.layer5.left_tree.left_tree.shortcut.1.weight", "module.layer5.left_tree.left_tree.shortcut.1.bias", "module.layer5.left_tree.left_tree.shortcut.1.running_mean", "module.layer5.left_tree.left_tree.shortcut.1.running_var", "module.layer5.left_tree.left_tree.shortcut.1.num_batches_tracked", "module.layer5.left_tree.right_tree.conv1.weight", "module.layer5.left_tree.right_tree.bn1.weight", "module.layer5.left_tree.right_tree.bn1.bias", "module.layer5.left_tree.right_tree.bn1.running_mean", "module.layer5.left_tree.right_tree.bn1.running_var", "module.layer5.left_tree.right_tree.bn1.num_batches_tracked", "module.layer5.left_tree.right_tree.conv2.weight", "module.layer5.left_tree.right_tree.bn2.weight", "module.layer5.left_tree.right_tree.bn2.bias", "module.layer5.left_tree.right_tree.bn2.running_mean", "module.layer5.left_tree.right_tree.bn2.running_var", "module.layer5.left_tree.right_tree.bn2.num_batches_tracked", "module.layer5.right_tree.root.conv.weight", "module.layer5.right_tree.root.bn.weight", "module.layer5.right_tree.root.bn.bias", "module.layer5.right_tree.root.bn.running_mean", "module.layer5.right_tree.root.bn.running_var", "module.layer5.right_tree.root.bn.num_batches_tracked", "module.layer5.right_tree.left_tree.conv1.weight", "module.layer5.right_tree.left_tree.bn1.weight", "module.layer5.right_tree.left_tree.bn1.bias", "module.layer5.right_tree.left_tree.bn1.running_mean", "module.layer5.right_tree.left_tree.bn1.running_var", "module.layer5.right_tree.left_tree.bn1.num_batches_tracked", "module.layer5.right_tree.left_tree.conv2.weight", "module.layer5.right_tree.left_tree.bn2.weight", "module.layer5.right_tree.left_tree.bn2.bias", "module.layer5.right_tree.left_tree.bn2.running_mean", "module.layer5.right_tree.left_tree.bn2.running_var", "module.layer5.right_tree.left_tree.bn2.num_batches_tracked", "module.layer5.right_tree.right_tree.conv1.weight", "module.layer5.right_tree.right_tree.bn1.weight", "module.layer5.right_tree.right_tree.bn1.bias", "module.layer5.right_tree.right_tree.bn1.running_mean", "module.layer5.right_tree.right_tree.bn1.running_var", "module.layer5.right_tree.right_tree.bn1.num_batches_tracked", "module.layer5.right_tree.right_tree.conv2.weight", "module.layer5.right_tree.right_tree.bn2.weight", "module.layer5.right_tree.right_tree.bn2.bias", "module.layer5.right_tree.right_tree.bn2.running_mean", "module.layer5.right_tree.right_tree.bn2.running_var", "module.layer5.right_tree.right_tree.bn2.num_batches_tracked", "module.layer6.root.conv.weight", "module.layer6.root.bn.weight", "module.layer6.root.bn.bias", "module.layer6.root.bn.running_mean", "module.layer6.root.bn.running_var", "module.layer6.root.bn.num_batches_tracked", "module.layer6.left_tree.conv1.weight", "module.layer6.left_tree.bn1.weight", "module.layer6.left_tree.bn1.bias", "module.layer6.left_tree.bn1.running_mean", "module.layer6.left_tree.bn1.running_var", "module.layer6.left_tree.bn1.num_batches_tracked", "module.layer6.left_tree.conv2.weight", "module.layer6.left_tree.bn2.weight", "module.layer6.left_tree.bn2.bias", "module.layer6.left_tree.bn2.running_mean", "module.layer6.left_tree.bn2.running_var", "module.layer6.left_tree.bn2.num_batches_tracked", "module.layer6.left_tree.shortcut.0.weight", "module.layer6.left_tree.shortcut.1.weight", "module.layer6.left_tree.shortcut.1.bias", "module.layer6.left_tree.shortcut.1.running_mean", "module.layer6.left_tree.shortcut.1.running_var", "module.layer6.left_tree.shortcut.1.num_batches_tracked", "module.layer6.right_tree.conv1.weight", "module.layer6.right_tree.bn1.weight", "module.layer6.right_tree.bn1.bias", "module.layer6.right_tree.bn1.running_mean", "module.layer6.right_tree.bn1.running_var", "module.layer6.right_tree.bn1.num_batches_tracked", "module.layer6.right_tree.conv2.weight", "module.layer6.right_tree.bn2.weight", "module.layer6.right_tree.bn2.bias", "module.layer6.right_tree.bn2.running_mean", "module.layer6.right_tree.bn2.running_var", "module.layer6.right_tree.bn2.num_batches_tracked", "module.layer1.0.weight", "module.layer1.1.weight", "module.layer1.1.bias", "module.layer1.1.running_mean", "module.layer1.1.running_var", "module.layer1.1.num_batches_tracked", "module.layer2.0.weight", "module.layer2.1.weight", "module.layer2.1.bias", "module.layer2.1.running_mean", "module.layer2.1.running_var", "module.layer2.1.num_batches_tracked", "module.layer3.root.conv.weight", "module.layer3.root.bn.weight", "module.layer3.root.bn.bias", "module.layer3.root.bn.running_mean", "module.layer3.root.bn.running_var", "module.layer3.root.bn.num_batches_tracked", "module.layer3.left_tree.conv1.weight", "module.layer3.left_tree.bn1.weight", "module.layer3.left_tree.bn1.bias", "module.layer3.left_tree.bn1.running_mean", "module.layer3.left_tree.bn1.running_var", "module.layer3.left_tree.bn1.num_batches_tracked", "module.layer3.left_tree.conv2.weight", "module.layer3.left_tree.bn2.weight", "module.layer3.left_tree.bn2.bias", "module.layer3.left_tree.bn2.running_mean", "module.layer3.left_tree.bn2.running_var", "module.layer3.left_tree.bn2.num_batches_tracked", "module.layer3.left_tree.shortcut.0.weight", "module.layer3.left_tree.shortcut.1.weight", "module.layer3.left_tree.shortcut.1.bias", "module.layer3.left_tree.shortcut.1.running_mean", "module.layer3.left_tree.shortcut.1.running_var", "module.layer3.left_tree.shortcut.1.num_batches_tracked", "module.layer3.right_tree.conv1.weight", "module.layer3.right_tree.bn1.weight", "module.layer3.right_tree.bn1.bias", "module.layer3.right_tree.bn1.running_mean", "module.layer3.right_tree.bn1.running_var", "module.layer3.right_tree.bn1.num_batches_tracked", "module.layer3.right_tree.conv2.weight", "module.layer3.right_tree.bn2.weight", "module.layer3.right_tree.bn2.bias", "module.layer3.right_tree.bn2.running_mean", "module.layer3.right_tree.bn2.running_var", "module.layer3.right_tree.bn2.num_batches_tracked", "module.layer4.root.conv.weight", "module.layer4.root.bn.weight", "module.layer4.root.bn.bias", "module.layer4.root.bn.running_mean", "module.layer4.root.bn.running_var", "module.layer4.root.bn.num_batches_tracked", "module.layer4.left_tree.root.conv.weight", "module.layer4.left_tree.root.bn.weight", "module.layer4.left_tree.root.bn.bias", "module.layer4.left_tree.root.bn.running_mean", "module.layer4.left_tree.root.bn.running_var", "module.layer4.left_tree.root.bn.num_batches_tracked", "module.layer4.left_tree.left_tree.conv1.weight", "module.layer4.left_tree.left_tree.bn1.weight", "module.layer4.left_tree.left_tree.bn1.bias", "module.layer4.left_tree.left_tree.bn1.running_mean", "module.layer4.left_tree.left_tree.bn1.running_var", "module.layer4.left_tree.left_tree.bn1.num_batches_tracked", "module.layer4.left_tree.left_tree.conv2.weight", "module.layer4.left_tree.left_tree.bn2.weight", "module.layer4.left_tree.left_tree.bn2.bias", "module.layer4.left_tree.left_tree.bn2.running_mean", "module.layer4.left_tree.left_tree.bn2.running_var", "module.layer4.left_tree.left_tree.bn2.num_batches_tracked", "module.layer4.left_tree.left_tree.shortcut.0.weight", "module.layer4.left_tree.left_tree.shortcut.1.weight", "module.layer4.left_tree.left_tree.shortcut.1.bias", "module.layer4.left_tree.left_tree.shortcut.1.running_mean", "module.layer4.left_tree.left_tree.shortcut.1.running_var", "module.layer4.left_tree.left_tree.shortcut.1.num_batches_tracked", "module.layer4.left_tree.right_tree.conv1.weight", "module.layer4.left_tree.right_tree.bn1.weight", "module.layer4.left_tree.right_tree.bn1.bias", "module.layer4.left_tree.right_tree.bn1.running_mean", "module.layer4.left_tree.right_tree.bn1.running_var", "module.layer4.left_tree.right_tree.bn1.num_batches_tracked", "module.layer4.left_tree.right_tree.conv2.weight", "module.layer4.left_tree.right_tree.bn2.weight", "module.layer4.left_tree.right_tree.bn2.bias", "module.layer4.left_tree.right_tree.bn2.running_mean", "module.layer4.left_tree.right_tree.bn2.running_var", "module.layer4.left_tree.right_tree.bn2.num_batches_tracked", "module.layer4.right_tree.root.conv.weight", "module.layer4.right_tree.root.bn.weight", "module.layer4.right_tree.root.bn.bias", "module.layer4.right_tree.root.bn.running_mean", "module.layer4.right_tree.root.bn.running_var", "module.layer4.right_tree.root.bn.num_batches_tracked", "module.layer4.right_tree.left_tree.conv1.weight", "module.layer4.right_tree.left_tree.bn1.weight", "module.layer4.right_tree.left_tree.bn1.bias", "module.layer4.right_tree.left_tree.bn1.running_mean", "module.layer4.right_tree.left_tree.bn1.running_var", "module.layer4.right_tree.left_tree.bn1.num_batches_tracked", "module.layer4.right_tree.left_tree.conv2.weight", "module.layer4.right_tree.left_tree.bn2.weight", "module.layer4.right_tree.left_tree.bn2.bias", "module.layer4.right_tree.left_tree.bn2.running_mean", "module.layer4.right_tree.left_tree.bn2.running_var", "module.layer4.right_tree.left_tree.bn2.num_batches_tracked", "module.layer4.right_tree.right_tree.conv1.weight", "module.layer4.right_tree.right_tree.bn1.weight", "module.layer4.right_tree.right_tree.bn1.bias", "module.layer4.right_tree.right_tree.bn1.running_mean", "module.layer4.right_tree.right_tree.bn1.running_var", "module.layer4.right_tree.right_tree.bn1.num_batches_tracked", "module.layer4.right_tree.right_tree.conv2.weight", "module.layer4.right_tree.right_tree.bn2.weight", "module.layer4.right_tree.right_tree.bn2.bias", "module.layer4.right_tree.right_tree.bn2.running_mean", "module.layer4.right_tree.right_tree.bn2.running_var", "module.layer4.right_tree.right_tree.bn2.num_batches_tracked".

thanks.

**Comment by maithal** [comment]
Hi,
Were you able to solve this issue?

**Comment by cg563** [comment]
My best guess would be the checkpoint is not a ResNet-18 model?

**Comment by maithal** [comment]
This issue was not with the checkpoint instead the model argument that I was passing. I was writing --model resnet18 which it never recognized due to case sensitiveness (since expected was --model ResNet18).

Thanks a lot again for quickly responding the issue.
