### ISSUE TITLE
I want to know in run_simba.py file, why can batchfile guarantee that attacks are carried out on images that are correctly classified?

### ISSUE THREAD

**Issue by Kitzzaaa** [cg563/simple-blackbox-attack#25]
I want to know in run_simba.py file, why can batchfile guarantee that attacks are carried out on images that are correctly classified?

**Comment by cg563** [comment]
The batch file is generated by running lines https://github.com/cg563/simple-blackbox-attack/blob/master/run_simba.py#L55-L63, which repeatedly samples data from the validation set as long as the batch of samples is not fully correctly classified. Does this help?
