### ISSUE TITLE
Problem on updating succs in simba_batch

### ISSUE THREAD

**Issue by ChengChen2020** [cg563/simple-blackbox-attack#26]
Hello,

I am trying to plot the average success rate against average query. When calculating success rate, I use

`res = torch.load('MY/PATH/FOR/SIMBA/RESULTS')`
`y = [res['succs'][:, i].sum() for i in range(res['succs'].shape[1])]`

It turns out `y` list is not monotonically increasing. It might be due to the updating of `succs` array in `simba_batch` as follows 

<img width="729" alt="image" src="https://user-images.githubusercontent.com/78533757/227822112-4cfedf68-d4bb-4876-ae1d-5fa90f794f2f.png">

For example, suppose we have `k = 100`, then when entering line 113, `succs[:, 99]` would be updated. In the next iteration when `k = 101`, if `remaining.sum() == 0`, `succs[:, 101:]` is updated, while leaving `succs[:, 100]` not updated.

I am wondering if there's any specific reason why only the first `k - 1` elements is updated in the `k`th iteration.

Thanks.

**Comment by cg563** [comment]
This seems like a bug to me, thanks for catching it! I will fix the bug by changing L113 to `succs[:, k]`.
