### ISSUE TITLE
How to load the dataset?

### ISSUE THREAD

**Issue by qilong-zhang** [cg563/simple-blackbox-attack#3]
Hi, 

I want to run the code, but I don't have the `.pth` file
```python
# this is to ensure all attacks are run on the same set of correctly classified images
batchfile = '%s/images_%s_%d.pth' % (args.sampled_image_dir, args.model, args.num_runs)
```
So the `.pth` file should make by myself? Thanks!

**Comment by cg563** [comment]
The .pth file will be generated automatically as long as you specify the --data_root parameter. Please close the issue if the code runs fine.

**Comment by qilong-zhang** [comment]
Thanks！I apologize for my negligence。

**Comment by MaybeJT** [comment]
Hi bro！Have you deal with the dataset problem？Should I download all ImageNet dataset？Or I just need to creat a new dictionary?

**Comment by cg563** [comment]
You do need the full ImageNet test set to generate a `.pth` file. After that you should be able to read from the `.pth` file every time.
